# Generated by Django 4.2 on 2024-08-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/default/default_profile_image.png', null=True, upload_to='images/profile_images/'),
        ),
    ]
